#!/usr/bin/env bash
# A script that displays Best School 10 times and hi after the 9th using while and if

count=0
while [ $count -lt 10 ]
do
	echo "Best School"
	if [ $count -eq 8 ]
	then
		echo "Hi"
	fi
	((count++))
done